name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: codebuild-CloudSmith-agent-benchmark-tests-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build Library
        run: npx lerna run build --scope=aws-cdk-lib